export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const REMOVE_TODO_REQUEST = 'REMOVE_TODO_REQUEST'
export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST'
export const COMPLETE_TODO_REQUEST = 'COMPLETE_TODO_REQUEST'